


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EMIS
    username: root
    password: JY@class4579
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  port: 8080


